fix(android): box shadow and border radius white border resolution
NativeScript/NativeScript pull request #10125
Opened 2022-12-07 13:02 UTC by vallemar

When you have a dark screen and you apply box-shadow and border radius you see a rather strange white border. Applying this change solves it. I haven't seen any difference on a clear screen, so I think it doesn't break anything

Old:
![Screenshot_2022-12-07-13-49-01-283-edit_org nativescript abllapp](https://user-images.githubusercontent.com/15719383/206185931-61c23c24-f87f-41ba-a28a-b2f7286bc593.jpg)

Fix:
![Screenshot_2022-12-07-13-47-43-779-edit_org nativescript abllapp](https://user-images.githubusercontent.com/15719383/206185897-555340e3-1949-44d7-9d7f-749e3980f80e.jpg)

2022-12-07 14:18 UTC, rigor789 commented
Mentioned on Discord already, just adding here for visibility:

The WHITE rect layer is added to mimic the web behavior:
![image](https://user-images.githubusercontent.com/879060/206202598-22a84072-6f7c-48ae-aa75-5eac4fdbe496.png)

So setting it to `TRANSPARENT` is redundant, as we might as well not even add the overlay layer in that case. A proposed solution is to check whether the view already has a background, and only in case it doesn't add the white rect overlay, otherwise skip adding the overlay layer at all.

2022-12-07 15:43 UTC, vallemar commented
@rigor789  I had misunderstood you, I thought it was just the passing of the color, now the layer will not be added if it already has a background

2022-12-27 17:14 UTC, vallemar commented
can we review this pr?

2022-12-27 17:18 UTC, rigor789 requested changes

2022-12-27 17:18 UTC, rigor789 commented on packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/BoxShadowDrawable.java
> +		if(!((BorderDrawable) this.wrappedLayer).hasBackgroundColor()){
This might be unsafe, `this.wrappedLayer` might not always be a BorderDrawable, so casting to it can lead to exceptions. A safer approach would be to check the type of `wrappedLayer`.

2023-03-17 11:36 UTC, vallemar commented
@rigor789 @NathanWalker I have updated the PR with the type check

2023-03-17 16:53 UTC, rigor789 submitted a review, later dismissed
Looks good to me, just left some small nits about the method naming. 👍

2023-03-17 16:55 UTC, rigor789 approved these changes

2023-03-17 17:52 UTC, rigor789 commented
Simplified the logic to hide the overlay layer when the wrapped drawable has a background color, image or gradient. The above issue was caused by changing the order of the `addLayer` calls mainly. Might still try not creating the layer at all - but the order of layers important.

2023-03-17 18:04 UTC, rigor789 commented
Refactored to not create the layer as originally intended - but preserving the order of layers now correctly.

2023-03-17 18:29 UTC, vallemar commented
@rigor789 oh sorry, I thought the order wouldn't matter and put it in an order that I thought was more readable

2023-03-17 21:50 UTC, NathanWalker approved these changes

2023-03-17 23:02 UTC, merged