fix (ios-view): resolves race condition when setting preferredContentSize on view controller
NativeScript/NativeScript pull request #10179
Opened 2023-01-19 21:55 UTC by AdamAtri

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
A race condition exists when showing a view modally on ios if that view has been assigned width and height.  In `_showNativeModalView` (@nativescript/core/ui/core/view/index.ios.ts, 459) `const controller` is assigned the value `this.viewController`. In the `handler` callback created on line 481, the width/height from the view are assigned to the `preferredContentSize` of the `controller`. However at the conclusion of `_showNativeModalView`, the `controller` variable is released, creating a race condition for the handler.

## What is the new behavior?
Making the perferredContentSize assignment on `this.viewController` instead of `controller` avoids a race condition.

2023-01-19 23:43 UTC, NathanWalker requested changes

2023-01-19 23:43 UTC, NathanWalker commented on packages/core/ui/core/view/index.ios.ts
> +							this.viewController.preferredContentSize = CGSizeMake(w, h);
Very nice thank you. Just above here on line 482 let's also change:
```
if (controller) {
```
to:
```
if (this.viewController) {
```
to be safe here as I've seen some varied race conditions around this handler as well.

2023-01-20 17:25 UTC, NathanWalker approved these changes

2023-01-20 19:02 UTC, AdamAtri commented
Rock on!!! My first commit to {N} core!

2023-01-21 04:24 UTC, merged