fix(ios): race conditions with nativeView
NativeScript/NativeScript pull request #10182
Opened 2023-01-21 18:25 UTC by NathanWalker

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

Under various view navigation conditions, anything from background-image css handling to processing of the nativeView can trigger with view bindings at times which lead to race conditions when the nativeView would have been destroyed and crashes such as:

```
  Unhandled Promise rejection: Cannot read property 'frame' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'frame' of null TypeError: Cannot read property 'frame' of null
  at uiColorFromImage (file: node_modules/@nativescript/core/ui/styling/background.ios.js:317:0)
  at file: node_modules/@nativescript/core/ui/styling/background.ios.js:167:0
```

## What is the new behavior?

iOS stability across broader diverse project/layout binding setups.

2023-01-22 09:16 UTC, shirakaba requested changes

2023-01-22 09:16 UTC, shirakaba commented on packages/core/ui/styling/background.ios.ts
> +	if (!nativeView) {
I think we shouldn't have to second-guess TypeScript - if the method args demand `nativeView` to be populated, we should be able to trust it. Can we handle this upstream of here instead somehow?

Same for the other methods putting a guard around nativeView when the method args specify a non-null, not undefined `nativeView`.

2023-01-22 17:06 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +	if (!nativeView) {
The problem in these cases is that it’s tied to a lifecycle which depending on view setup is not guaranteed order - largely due to how different flavors trigger and apply their view bindings.

2023-01-23 09:18 UTC, farfromrefug commented on packages/core/ui/styling/background.ios.ts
> +	if (!nativeView) {
@NathanWalker i agree with @shirakaba i think most of those are unecessary.
If i take the example of `adjustLayersForScrollView` and where it is used. It is used in ScrollView on scroll event where there is a test for `nativeView instanceof UIScrollView` so the test in `adjustLayersForScrollView` is uncessary and in a sense makes things slower by adding a if test

2023-01-23 18:24 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +	if (!nativeView) {
Thanks for feedback @farfromrefug @shirakaba I'll see if can pair it down to resolve upstream for the single issue mentioned `uiColorFromImage` which is the key issue here.

2023-01-23 18:35 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +	if (!nativeView) {
This is fixed up for the isolated case now and allowed this to improve since this is a case where image request can be aborted/canceled or fail which should not allow this crash to occur.

2023-01-23 19:57 UTC, rigor789 approved these changes

2023-01-23 20:08 UTC, merged