fix(android): Change The android api path reference from 17 to 33.
NativeScript/NativeScript pull request #10209
Opened 2023-02-12 16:02 UTC by KunaalMangal

Change The android api path reference from 17 to 33 in types-android/src/lib/android.d.ts for accessing latest android api.

![image](https://user-images.githubusercontent.com/47212486/218322122-e6a2c0f9-931b-4930-91a3-ac678563fb05.png)

2023-02-13 10:28 UTC, rigor789 commented
Marking this as a draft, as I'd like to bring this up on our next TSC Meeting (Technical Steering Committee).

I agree we should change the default API level, however the default should likely be set to `API30`, and then changed to `API31` around Nov 2023 to match the `targetSdk` requirements (reference: https://apilevels.com/)

2023-02-16 15:38 UTC, NathanWalker requested changes

2023-02-16 15:38 UTC, NathanWalker commented on packages/types-android/src/lib/android.d.ts
> +/// <reference path="./android-33.d.ts" />
Per @rigor789 mention, please use 30 as it's the current recommendation from Google.
```suggestion
/// <reference path="./android-30.d.ts" />
```

2023-02-16 16:58 UTC, KunaalMangal commented
@cla-bot check

2023-02-16 18:40 UTC, KunaalMangal commented
@cla-bot check

2023-02-21 05:05 UTC, NathanWalker approved these changes

2023-02-21 23:19 UTC, merged