feat: Initial WinterCG modules
NativeScript/NativeScript pull request #10471
Opened 2024-01-08 06:00 UTC by triniwiz

2024-01-08 12:59 UTC, shirakaba requested changes
Thanks so much for leading the charge on this. It's a crazy amount of work and I'm looking forward to making WinterCG conformance a reality.

I've done a quick review of the areas I understand (so, ignoring Android), but my overall impression is:

* The PR is too big to safely review.
  * Can we break it down into more manageable pieces? GitHub's review interface is crawling 🫠
* It has coupling to V8 and JSI.
  * With the new Node-API-based NativeScript on the way, I worry that this effort would need to be repeated all over again, so I would prefer if we could take an engine-agnostic approach, i.e. no usage of V8 and JSI APIs.
* It looks like a lot of extra complication in build tooling, introducing makefiles and Rust (and a lot more logic in C++-land), which may make it harder to set up on CI and get building on other people's machines, and may slow down builds.
  * Would it be okay to sacrifice some performance in order to simplify the architecture? I'd prefer if we were in a position to help you maintain this 😅

Discussions to be had:
* Is there a reasonable, easy path to opt-in/opt-out of APIs?
  * This is maybe not a deal-breaker, but if it's within reach, that'd be of interest.
* Does this need to live in Core?
  * Core is already complicated to maintain. Could each API perhaps be done as a plugin?
* Would some of these modules be just as good as a Webpack polyfill? Given that JS polyfills exist for these, it'd be a very fair tradeoff for simplicity.

Again, really thanks for the draft to give us something concrete to discuss. Really hope to land this in some way.

2024-01-08 12:59 UTC, shirakaba commented on packages/core/src-native/ios/NativeScript.podspec
> +    s.vendored_frameworks = "NativeScript.xcframework"
This seems to vend `NativeScript.xcframework`. How were we handling that before, and what's changed now?

It feels like this stuff should be a separate standalone PR. As they're all new files, we can't tell in the git histroy whether anything has changed specifically for WinterCG.

2024-01-08 12:59 UTC, shirakaba commented on packages/core/url/index.ts
> +require('../native-helpers');
Is there anything we can do to avoid side-effects? This kind of pattern causes a lot of trouble, making it harder to migrate to new bundlers, tree-shake, opt-out, etc.

2024-01-08 12:59 UTC, shirakaba commented on packages/core/url/index.ts
> +import './url-search';
Again, importing for effects is a troublesome pattern if we can possibly avoid it. Though it is attractive to avoid changing the code of the URLSearchParams polyfill.

2024-01-08 12:59 UTC, shirakaba commented on packages/core/globals/index.ts
> +		installPolyfills('url', ['URL']);
I'd prefer to separately polyfill each of URL, URLSearchParams, etc. so that we don't have to rely upon side-effects in the URL module itself.

2024-01-08 12:59 UTC, shirakaba commented on tools/scripts/build-rust-android.sh
> +NDK_HOST="darwin-x86_64"
Is this build only gonna work on Intel and Rosetta? Wonder if it can be made more platform-agnostic.

2024-01-08 12:59 UTC, shirakaba commented on tools/scripts/copy-rust-android.sh
> +#! /bin/bash
Let's make the script fail upon any command exiting with a non-zero status code.

```suggestion
#! /bin/bash
set -e
```

2024-01-08 12:59 UTC, shirakaba commented on tools/scripts/build-rust-headers.sh
> +#!/bin/bash
Let's make the script fail upon any command exiting with a non-zero status code.

```suggestion
#! /bin/bash
set -e
```

2024-01-08 12:59 UTC, shirakaba commented on tools/scripts/build-rust-android.sh
> +#!/bin/bash
Let's make the script fail upon any command exiting with a non-zero status code.

```suggestion
#! /bin/bash
set -e
```

2024-01-08 12:59 UTC, shirakaba commented on packages/ui-mobile-base/android/widgets/src/main/jniLibs/arm64-v8a/libnativescriptcore.so
I worry about having to maintain native libs. It makes the build process a lot more complicated. I'd prefer to be in a position where we don't need extra expertise to help you maintain these features 🙇‍♂️

2024-01-08 12:59 UTC, shirakaba commented on packages/ui-mobile-base/android/widgets/src/main/cpp/include/nativescript_core.h
> +/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */
If these files are generated by cbindgen, should they be committed to source in the first place? What's the usual approach?

2024-01-08 12:59 UTC, shirakaba commented on Cargo.toml
> +[workspace]
Congrats on the first use of Rust in Core 🥳

I would say, however, that I'm worried about extra build tooling as it increases the expertise needed to maintain Core.

2024-01-08 13:05 UTC, triniwiz commented on packages/core/src-native/ios/NativeScript.podspec
> +    s.vendored_frameworks = "NativeScript.xcframework"
This was needed to make the build happy when doing the cpp builds, the hope is when we moved to pod or spm (gotta test this one) we can drop this pod

2024-01-08 13:06 UTC, triniwiz commented on packages/core/url/index.ts
> +require('../native-helpers');
I have a few ideas to clean this up

2024-01-08 13:08 UTC, triniwiz commented on packages/core/url/index.ts
> +import './url-search';
This can move move but this polyfill is only temp until the `URLSearchParams` pr is merged in the rust crate

2024-01-08 13:08 UTC, triniwiz commented on packages/core/url/index.ts
> +export class URL {
Ok sounds good

2024-01-08 13:11 UTC, triniwiz commented on tools/scripts/build-rust-android.sh
> +NDK_HOST="darwin-x86_64"
This works on the m1 afaik they didn't publish a `darwin-aarch64`

2024-01-08 13:12 UTC, triniwiz commented on packages/ui-mobile-base/android/widgets/src/main/jniLibs/arm64-v8a/libnativescriptcore.so
I can remove these from as they will be generated when calling the build cmd

2024-01-08 13:13 UTC, triniwiz commented on packages/ui-mobile-base/android/widgets/src/main/cpp/include/nativescript_core.h
> +/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */
This can be ignored as well

2024-01-08 13:23 UTC, triniwiz commented
Sure we can sacrifice the performance to simplify the architecture so if needed I can do it as Android and iOS libs.

1. Is there a reasonable, easy path to opt-in/opt-out of APIs?

Turn it into plugins/packages

2. Does this need to live in Core?
No up to the tsc to decide 

3. Core is already complicated to maintain. Could each API perhaps be done as a plugin?
Yeah 🤷🏽

Would some of these modules be just as good as a Webpack polyfill (or even done by deferring to spinning up the system JS runtime, like JSC)?
Yeah we can but will lose some performance here, again up to the tsc.

2024-01-08 14:07 UTC, farfromrefug commented
@triniwiz what performance do we loose by using webpack polyfills? I dont see what it will change

To me if those are moved out of this repo we can use rust/c++ as we don't bloat this repo. Now tbh for such libraries is rust really needed? What does it bring to the table instead of simple c++ modules?

If understand correctly where we'll loose in performance is if we become engine agnostic and don't directly use v8 apis. Am i right @triniwiz ? But do we really need that for those APIs? I mean we rarely use those high framerate computing or heavy computation like done in @nativescript/canvas.

Also to point out that this PR is adding around 90mb of so libs which should not be in here

2024-01-09 19:44 UTC, closed without merging

2024-01-09 19:44 UTC, NathanWalker commented
Moved here: https://github.com/NativeScript/winter-cg