Segmented bar
NativeScript/NativeScript pull request #10474
Opened 2024-01-13 16:29 UTC by kefahB

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ x] All existing tests are passing: I have wort the tests but I couldn't figure out a way to compare the background color, I've manually well tested the changes
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
On Android, the `selectedBackgroundColor` doesn't work at all (on first load and on select index change), we can not see the selected item.

## What is the new behavior?
The background color does appear at the first load and on selected index changed

Fixes/Implements/Closes #10472 .

I have added a new property for both platforms to control `selectedTextColor` that can be set for more control of the selected state.

2024-01-13 17:04 UTC, NathanWalker requested changes
Nice PR! Small comment.

2024-01-13 17:04 UTC, NathanWalker commented on packages/core/ui/segmented-bar/index.ios.ts
> +import { Utils } from '../../index';
Better to use direct deep imports here instead of the "barrels" like `Utils`. So best to use iOSNativeHelper.
This is due to bundling - core needs to stick to direct imports everywhere inside core.

2024-01-13 20:16 UTC, kefahB commented on packages/core/ui/segmented-bar/index.ios.ts
> +import { Utils } from '../../index';
Fixed

2024-01-18 08:16 UTC, kefahB commented on packages/core/ui/segmented-bar/index.ios.ts
> +import { MajorVersion } from 'utils/ios';
@NathanWalker this is what you meant ?

2024-01-19 18:34 UTC, NathanWalker commented on packages/core/ui/segmented-bar/index.ios.ts
> +import { MajorVersion } from 'utils/ios';
All symbols should be imported via relative imports to their exact location when working within core source. 'utils/ios' is not a relative import. I pushed up the correct usage there for you and will get this merged, thanks again.

2024-01-19 18:38 UTC, NathanWalker approved these changes

2024-01-19 18:39 UTC, merged

2024-03-12 11:50 UTC, CatchABus commented
@kefahB This PR broke SegmentedBar selection color styling.
Let me note that `selectedBackgroundColor` worked on my device without needing this PR.

This is how it used to be:
![Screenshot_20240312-133934 (1)](https://github.com/NativeScript/NativeScript/assets/55595100/b53677bc-8a54-462d-bd39-84f34575126c)

This is how it is now, after these changes:
![Screenshot_20240312-134157 (2)](https://github.com/NativeScript/NativeScript/assets/55595100/1043b9dc-99d0-4592-93dc-a8adbb1aff22)

2024-03-12 12:17 UTC, CatchABus commented on packages/core/ui/segmented-bar/index.android.ts
> +						view.setBackgroundColor(unselectedBackgroundColor);
@kefahB Still, setting background color here seems wrong as it applies color to entire segment button (it's just as my screenshots indicate). Would it work on your device if we removed those `setBackgroundColor` calls?

2024-03-12 12:18 UTC, CatchABus reviewed
Setting background color this way seems to cause the problem.

2024-03-12 12:20 UTC, kefahB commented on packages/core/ui/segmented-bar/index.android.ts
> +						view.setBackgroundColor(unselectedBackgroundColor);
I need time to check this because I am. not on the project, but at the time I does not working! Please not that also we can keep it as optional to give same apparence oh both platforms

2024-03-12 12:23 UTC, kefahB commented
What do you suggest ?

2024-03-15 19:37 UTC, CatchABus commented
> What do you suggest ?

We can leave this be for now but I think we should work on it more and get rid of hackish solutions. If possible, let us know of the phone model and OS version where the problem occured in case we revisit this.