fix(core): remove multiple event/gesture name handling
NativeScript/NativeScript pull request #10539
Opened 2024-05-05 03:05 UTC by shirakaba

This PR is based onto the following PRs that are in review:

- [ ] #10537 (first PR)
- [ ] #10538 (second PR)

I'd suggest reviewing this by subtracting the three commits from those PRs.

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

Currently, it is possible to listen for plural events by passing a comma-delimited series of event names (which may optionally be surrounded by whitespace):

```js
observable.addEventListener("propertyChange,loaded");
// Adds listeners for the "propertyChange" and "loaded" events

observable.addEventListener("propertyChange  ,  loaded");
// Adds listeners for the "propertyChange" and "loaded" events
```

It is also possible to observe plural gestures, but due to bugs in the implementation, it is only possible via a plural enum and not a plural string.

```js
observable.addEventListener("tap,doubleTap");
// Fails.
//
// The fromString() method in `gestures-common.ts` doesn't split on commas, so
// the gesture name here coerces to `undefined`, thus
// Observable.prototype.addEventListener() throws a TypeError saying
// "Event name(s) must be a string.".

observable.addEventListener(GestureTypes.tap & GestureTypes.doubleTap);
// Succeeds, though will cease to be allowed if #10537 (which disallows numeric
// event names) is merged.
//
// At the time of writing, adds a single observer that manages two GestureHandlers:
// - one for the "tap" gesture
// - one for the "doubleTap" gesture
```

## What is the new behavior?

We now interpret event names as-is, corresponding to a singular event listener or observer. So we no longer trim event names, nor split on commas. As this PR is based on #10537, we only accept string names, so don't support enums at all (so avoid having to special-case plural enums).

```js
observable.addEventListener("propertyChange,loaded");
// Adds a (probably not very useful) listener for the non-existent "propertyChange,loaded" event

observable.addEventListener("  propertyChange  ,  loaded  ");
// Adds a (probably not very useful) listener for the non-existent "  propertyChange  ,  loaded  " event

observable.addEventListener("tap,doubleTap");
// Adds a (probably not very useful) listener for the non-existent "propertyChange,loaded" event.
// Since it doesn't exactly match any gesture name, it is indeed an event listener and not a gesture observer.

observable.addEventListener("  propertyChange  ,  loaded  ");
// Adds a (probably not very useful) listener for the non-existent "  propertyChange  ,  loaded  " event
// Since it doesn't exactly match any gesture name, it is indeed an event listener and not a gesture observer.
```

## Breaking changes

This PR drops support for listening for:
- plural events, e.g. "propertyChange,loaded"
- plural gestures, e.g. `GestureTypes.tap & GestureTypes.doubleTap` (though support for this form should be removed in #10537, and the string form "tap,doubleTap" was never working to begin with).

### Impact

From TSC discussions, it doesn't seem that this feature is commonly, if ever, used, so impact may be low in practice. Certainly, it wasn't used anywhere within Core except in some test cases (which I've updated accordingly).

### Migration steps

Any plugins or userland code using plural event/gesture names should instead split them into singular names and listen for them individually.

2024-05-05 06:41 UTC, farfromrefug requested changes
@shirakaba shouldn't the regexp for names be removed now ?
The rest looks good

2024-05-05 07:55 UTC, farfromrefug approved these changes

2024-05-05 08:11 UTC, shirakaba commented
@farfromrefug Thanks for the approval! I pushed a follow-up commit as I can't be sure about `isGesture()`, so will avoid introducing a very hard-to-track-down breakage for now. If we're feeling brave, we can remove the `.trim().toLowerCase()` for extra performance, I just don't know whether it'll break some renderer. Do you think it's worth the risk?

2024-05-07 01:19 UTC, NathanWalker approved these changes

2024-05-07 01:20 UTC, merged