Fix extending android application and activity
NativeScript/NativeScript pull request #8898
Opened 2020-09-25 09:07 UTC by mapo80

This change fixes this issue: https://github.com/NativeScript/NativeScript/issues/8893

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

2020-09-28 19:41 UTC, mapo80 commented
@cla-bot check

2020-09-28 19:56 UTC, rigor789 requested changes
Thanks for the PR!

Left a note with a suggestion, so we keep the config very similar to previous configs - just extending it, rather than renaming the variables.

Other than that, It should be done for all configs for consistency.

2020-09-28 19:56 UTC, rigor789 commented on packages/webpack/templates/webpack.angular.js
> +  const appEntries = Object.assign({ bundle: entryPath }, entries);
I think we should just keep the same naming as before. Just saw that the original `env` spread is `const` but, can add

```js
let {
    appComponents = [],
    entries = {}
} = env;

entries = Object.assign({ bundle: entryPath }, entries);
appComponents = appComponents.concat([
    "@nativescript/core/ui/frame", "@nativescript/core/ui/frame/activity"
]);
```

2020-09-29 15:26 UTC, mapo80 commented on packages/webpack/templates/webpack.angular.js
> +  const appEntries = Object.assign({ bundle: entryPath }, entries);
Original env is a const, do you want to change it?

2020-09-29 15:43 UTC, rigor789 commented on packages/webpack/templates/webpack.angular.js
> +  const appEntries = Object.assign({ bundle: entryPath }, entries);
I think we can just add it below, as a mutable/let spread. 
```js
const {
 // ...
} = env;

let {
    appComponents = [],
    entries = {}
} = env;
```

It could possibly stay a const too - since array operations/object mutations don't replace the variable itself.

So perhaps
```js
const {
 // ...
  appComponents = [];
  entries = {}
} = env;

// assign { bundle: entryPath } to entries which is {} by default, but still assign entries at the end
// to allow overriding the bundle entry too
Object.assign(entries, { bundle: entryPath }, entries);
appComponents.push("@nativescript/core/ui/frame", "@nativescript/core/ui/frame/activity");
```

2020-09-30 07:21 UTC, mapo80 reviewed
For me is ok!

2020-10-02 06:15 UTC, mapo80 commented
I've pushed changes. If it's ok can you merge?

2020-10-13 09:57 UTC, mapo80 commented
news?

2020-10-13 11:33 UTC, rigor789 commented
@mapo80 this is looking good, we just want to add it to all the other configs as well before we merge it. If you can do it, that'd be awesome - otherwise when we have the chance we'll add and then merge.

2021-01-29 21:11 UTC, NathanWalker approved these changes

2021-01-29 21:12 UTC, merged