fix for splice index > length
NativeScript/NativeScript pull request #8900
Opened 2020-09-25 10:54 UTC by farfromrefug

In javascript you can call splice with an index > length. The result is a push.
But when you do that ObservableArray index will be wrong and thus user logic will fail.
Example:
```ts
// obsarray = [0];
obsarray.splice(2, 0, 1);
// this works, the inner array is now [0,1]
// however 'change' is called with index = 2
// when the use tries to do obsarray.getItem(eventData.index) -> crash
```
We have that issue with `svelte-native` and the `spans` `ObservableArray` of `FormattedString`

2020-09-25 18:33 UTC, NathanaelA requested changes

2020-09-25 19:18 UTC, NathanaelA commented on packages/core/data/observable-array/index.ts
> +			index: Math.min(start, length),
Maybe it should be `Math.min(start, this._array.length-1)` so it takes in account the current length of the array when it returns the value.   The only other corner case I can think of is if you delete the last item, your index = -1...   But maybe that should be the case, since their is no valid index...

2020-09-25 19:26 UTC, farfromrefug commented on packages/core/data/observable-array/index.ts
> +			index: Math.min(start, length),
I think it is the same. Length is the size before addition 
Will look at deletion

2020-09-25 21:54 UTC, NathanaelA commented on packages/core/data/observable-array/index.ts
> +			index: Math.min(start, length),
Yes, Length is the size before the addition OR deletion.   So in addition cases the prior length would be good!    However in deletions it could very frequently be wrong. 

So instead use the `current array length - 1`  -- so that it is always a valid index except in the case you delete everything and there is only zero items...    In that case it would return -1, in that specific corner case you can't do anything with the index anyway.    So I think that is valid return in that case anyways.

So my suggestion that would fix both cases (add & delete) is 
```
index: Math.min(start, this._array.length-1);
```
Unless you have a better idea; this seems to solve both your issue that you found and the opposite issue that I just found.  :grinning:

2020-09-26 07:26 UTC, farfromrefug commented on packages/core/data/observable-array/index.ts
> +			index: Math.min(start, length),
Oh i see now. Thanks

2020-09-27 16:09 UTC, NathanaelA approved these changes

2020-09-27 16:20 UTC, merged

2020-09-30 14:37 UTC, maxroehrl commented
@farfromrefug This MR causes a crash if `this._array.length === 0` after the splice because then we call `notify({ index: -1, ... })`.

2020-09-30 15:47 UTC, farfromrefug commented
@maxroehrl what crash ? can you specify the example where it crashes?

2020-09-30 17:38 UTC, maxroehrl commented
In a listview where the items are an observable array like `items = new ObersavableArray([{id: 1}]);`

Then after fetching some data I use `items.splice(0, 1, ...newData);`  to remove the placeholder item `{id: 1}`.

There is no error message but the debugger cannot step over the splice call after your change.

2020-09-30 18:10 UTC, farfromrefug commented
@maxroehrl thank i see! Will fix it

2020-09-30 18:28 UTC, farfromrefug commented
@maxroehrl  https://github.com/NativeScript/NativeScript/pull/8921

2020-10-01 02:40 UTC, NathanWalker commented
@maxroehrl published in `7.0.9` - thanks for fix @farfromrefug 👍

2020-10-17 23:11 UTC, NathanaelA commented
@maxroehrl & @farfromrefug - I found a couple other corner cases that this PR broke.   I have updated the code with PR #8968 if you both can double check that this fix doesn't break your stuff, I believe the new added tests should catch either of your prior issues.

2020-10-18 14:47 UTC, maxroehrl commented
@NathanaelA I tested your your code and it also works for me.