feat: Repeater multiple item templates implementation
NativeScript/NativeScript pull request #8981
Opened 2020-10-22 18:34 UTC by DimitrisRK

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
Repeater does not support multiple item templates. This is a quite a limitation for NativeScript Core since it does not support any other iteration methods.

## What is the new behavior?
This is my previous patch with further improvements and additions along with NativeScript 7 support.
Repeater will support multiple item templates using keys, just like ListView.
Both a sample and tests are included.

Implements #3781 .

2020-10-22 18:43 UTC, DimitrisRK commented
@cla-bot check

2020-10-22 18:50 UTC, DimitrisRK commented
@cla-bot check

2020-10-22 19:29 UTC, DimitrisRK commented
@cla-bot check

2020-10-22 19:43 UTC, DimitrisRK commented
I apologize for this spam of cla-bot. I fixed commit author details and CLA problem is gone.

2020-10-25 18:01 UTC, NathanWalker approved these changes
Great work @DimitrisRK thank you.

2020-10-26 01:45 UTC, NathanWalker requested changes

2020-10-26 01:45 UTC, NathanWalker commented on package.json
> +		"markdown-snippet-injector": "^0.2.4",
@DimitrisRK Could you just remove this dependency? Looks like maybe accidentally added. You can also rebase in latest master as it will fix CI error (node 15 was released and we just needed to pin travis to 14 so that's on master now).

2020-10-26 01:45 UTC, NathanWalker commented on apps/automated/package.json
> +    "@nativescript/android": "7.0.1",
You can actually discard these package changes. We typically won't commit runtime changes to the apps since these will always dynamically add latest runtime for each contributor running the apps.

2020-10-26 01:45 UTC, NathanWalker commented on apps/ui/package.json
> +    "@nativescript/android": "7.0.1",
discard this change as well

2020-10-26 08:59 UTC, DimitrisRK commented
@NathanWalker All done, thank you very much for guidance!

2020-10-27 03:13 UTC, NathanWalker approved these changes

2020-10-27 03:13 UTC, merged