fix: faster colors handling
NativeScript/NativeScript pull request #9001
Opened 2020-11-01 11:04 UTC by farfromrefug

Also know the rework parser shares the same known colors  (faster, smaller bundle)
There are some eslint fixes in there hope it is fine

2020-11-04 17:15 UTC, NathanWalker requested changes

2020-11-04 17:15 UTC, NathanWalker commented on packages/core/css/parser.ts
> +import { getKnownColor } from "color/known-colors";
Thanks for this @farfromrefug - Let's make this relative import instead of barrel.

2020-11-04 18:13 UTC, farfromrefug commented on packages/core/css/parser.ts
> +import { getKnownColor } from "color/known-colors";
Sorry did not see that. Vscode did that ;)

2020-11-06 19:33 UTC, NathanWalker approved these changes
Excellent thank you 💯

2020-11-10 01:00 UTC, merged