fix: color date/time ios14 tests
NativeScript/NativeScript pull request #9019
Opened 2020-11-09 22:57 UTC by NathanaelA

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.

## What is the current behavior?
iOS 14 removed support for text color on Date/Time except for the Wheel.   Tests were trying to read the color attribute directly on iOS 14 to compare it to what was set; which of course then failed as the Date/Time items are not using the wheel.

## What is the new behavior?
Fixes both tests to detect if on iOS 14, and then ignore that test.

2020-11-10 00:41 UTC, NathanWalker requested changes

2020-11-10 00:41 UTC, NathanWalker commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +import {Device} from "../../../../../packages/core";
Change this to: `import { Device } from '@nativescript/core';`

2020-11-10 00:41 UTC, NathanWalker commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +			const SUPPORT_TEXT_COLOR = parseFloat(platform.Device.osVersion) < 14.0;
Just use `Device` import here while in here and since imported above. `platform.Device` > `Device`

2020-11-10 00:41 UTC, NathanWalker commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +				this.testView.color = new color.Color('red');
While in here perhaps update `new color.Color` > `new Color` and just update to import from the barrel as well since in same file here. Cleanup as we go.

2020-11-10 05:56 UTC, NathanaelA commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +import {Device} from "../../../../../packages/core";
LOL, this never should have been added; my editor must have been trying to be smart...

2020-11-10 05:57 UTC, NathanaelA commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +			const SUPPORT_TEXT_COLOR = parseFloat(platform.Device.osVersion) < 14.0;
Actually `Device` should never have been added, `platform.Device` should be correct as `platform` is already imported because of other checks needed in this file.

2020-11-10 06:16 UTC, NathanaelA commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +import {Device} from "../../../../../packages/core";
This was removed in latest commit.

2020-11-10 06:17 UTC, NathanaelA commented on apps/automated/src/ui/date-picker/date-picker-tests.ts
> +				this.testView.color = new color.Color('red');
Updated Color to use Barrel in both date & time picker tests.

2020-11-11 07:13 UTC, NathanWalker approved these changes

2020-11-11 07:14 UTC, merged