faster  style-scope setPropertyValues
NativeScript/NativeScript pull request #9083
Opened 2020-12-02 16:03 UTC by farfromrefug

That Pr makes the style-scope `setPropertyValues` much faster. It tries not to do so many loops.
The only real change is the fact that i dont freeze the `_appliedPropertyValues`  object anymore. I need that to go faster and as the object is not used outside of that function it does not seem to make a difference.

Now do we have tests which would ensure that is not breaking anything?

2020-12-02 16:28 UTC, NathanaelA requested changes
I would leave this alone as the idea here is to let developers know that even though this is available on the Prototype scope it is read only!

2020-12-02 16:45 UTC, NathanaelA requested changes
Have you benchmarked this against the current code, I'd be interested to know what savings (if any) you create with this refactor.

2020-12-02 16:45 UTC, NathanaelA commented on packages/core/ui/styling/style-scope.ts
> +		const oldProperties = this._appliedPropertyValues || {};
This can be left the way it was, no need to add the `|| {}` as _appliedPropertyValues ALWAYS has a value.  It is defaulted to EmptyPropertyBag  on construction.

2020-12-02 16:45 UTC, NathanaelA commented on packages/core/ui/styling/style-scope.ts
> +	_appliedPropertyValues: Record<string, unknown>;
This should be reverted back, it is letting other developers know that if they access it -- it is read only.

2020-12-02 16:45 UTC, NathanaelA commented on packages/core/ui/styling/style-scope.ts
> -			if (!(property in newPropertyValues)) {
If I read your code correctly You do realize that without this check, you can end up doing double the work on all css properties.   Example: Say the property is `background` then Line 587 will be triggered, then later 598 causing the new background to be applied twice; if the background property is long running you created extra runtime overhead for the same set value.   The purpose of this check is to eliminate double setting of the value since it will be set below at line 598.

2020-12-02 17:40 UTC, farfromrefug commented
@NathanaelA no benchmark no. Just globally faster as you loop through new props only once and loop through less old properties.
Would be nice to have benchmarks around all that properties/CSS thing

2020-12-03 11:20 UTC, farfromrefug commented on packages/core/ui/styling/style-scope.ts
> +	_appliedPropertyValues: Record<string, unknown>;
@NathanaelA then we should make it private instead ? the readonly think makes tsc not happy when i delete properties on `oldProperties`

2020-12-03 11:26 UTC, farfromrefug commented on packages/core/ui/styling/style-scope.ts
> -			if (!(property in newPropertyValues)) {
@NathanaelA good catch. the issue is up. I mean in fact any value from `newPropertyValues` can be removed from `oldProperties`, right? So i should simply add the `delete oldProperties[property];` for all values in the loop of  `newPropertyValues`

2020-12-03 17:44 UTC, NathanaelA commented on packages/core/ui/styling/style-scope.ts
> +	_appliedPropertyValues: Record<string, unknown>;
Yeah, you are right, I don't see any reason at this point this needs to be public.     Good idea!   Mark it as private.

2020-12-03 17:45 UTC, NathanaelA commented on packages/core/ui/styling/style-scope.ts
> -			if (!(property in newPropertyValues)) {
I believe so...  The tests will tell us for certain as the Styling code is quite complicated in some areas on what it expects/needs.

2020-12-03 17:55 UTC, NathanaelA commented
You can add some bench marks into the code; rename the existing function to `_setPropertyValues` and create a new `setPropertyValues` and add `const x = Date.now(); this._setPropertyValues(...); y = Date.now(); console.log(y-x);` it isn't totally precise but it will give a rough idea  of the speed.    

Then run it using the prior code with a heavy css app (or maybe even the automated app) a couple times and copy the numbers.   Then use your new code with the same apps.

This will give you a pretty good idea if this is faster, slower or even majorly faster/slower.

2020-12-03 18:44 UTC, rigor789 commented
> You can add some bench marks into the code; rename the existing function to _setPropertyValues and create a new setPropertyValues and add const x = Date.now(); this._setPropertyValues(...); y = Date.now(); console.log(y-x); it isn't totally precise but it will give a rough idea of the speed.

@farfromrefug @NathanaelA even simpler: 

```js
console.time('setPropertyValues')
this._setPropertyValues(...);
console.timeEnd('setPropertyValues')
```
Will print the time it has taken :D

2022-08-23 20:59 UTC, NathanWalker commented
@farfromrefug I've updated this PR with latest main and looks like just 4 tests are affected by these changes:
```
  === ALL TESTS COMPLETE ===
  1632 OK, 4 failed
  DURATION: 22370.61 ms
  === END OF TESTS ===
  Test: STYLE.test_css_calc_and_variables FAILED: Stack - width === 10% At /value actual: '1' and expected: '0.1' differ.
  Test: STYLE.test_css_variable_fallback FAILED: undefined-css-variable-without-fallback Actual: <#0000FF>(string). Expected: <undefined>(undefined)
  Test: STYLE.test_css_variables FAILED: Cannot read property 'hex' of undefined
  Test: STYLE.test_nested_css_calc_and_variables FAILED: Stack - width === 200% At /value actual: '1' and expected: '2' differ.
```
Would you be able to peek sometime? We can queue this up to include in 8.4. It does appear that these changes will make the tests finish in faster time which leads me to believe there are some perf gains here.

2022-08-24 16:13 UTC, farfromrefug commented
@NathanWalker all tests are now passing. Hope i got it all right. The issue was that css vars/exps need to be handled separately in the sense that all css vars must be evaluated before we can evaluate css expressions. I added a comment so we dont forget about it anymore.
It should not make things any slower

2022-09-07 23:47 UTC, merged