fix(android): refactor to make less calls to native
NativeScript/NativeScript pull request #9119
Opened 2020-12-30 15:07 UTC by farfromrefug

This PR simplifies the android code a bit to make less calls to android native constants. Thus less JNI bridge calls =>faster

2020-12-30 16:24 UTC, NathanaelA requested changes

2020-12-30 16:24 UTC, NathanaelA commented on packages/core/ui/core/view/index.android.ts
> +
I would also add the `LEFT` and `TOP` up here so they are no longer magic numbers.   Your refactor leaves `.LEFT` and `.TOP` in the source as magic numbers so people have no idea why they are these values.

2020-12-30 16:24 UTC, NathanaelA commented on packages/core/ui/core/view/index.android.ts
> +		const weight = lp.weight;
I would eliminate these two extra variables.   And revert the rest of the statements back to using `lp.gravity` and `lp.weight` as all you have done is added additional memory usage (which has to be GC'd) for no purpose and now have mixed values throughout below.  You assign `lp.gravity` from `gravity` on line 872.   This just confuses the source for people who later read it.

2020-12-30 16:24 UTC, NathanaelA commented on packages/core/ui/core/view/index.android.ts
> +		const height = lp.height;
Same comment as above.

2020-12-30 16:24 UTC, NathanaelA commented on packages/core/ui/core/view/index.android.ts
> +					lp.gravity = 3 | (gravity & VERTICAL_GRAVITY_MASK); // android.view.Gravity.LEFT
What is `3`, `1`, `5`, `7`.   Definitely would be better to create the `const` at the top so that the code is easier to read.

2020-12-30 19:26 UTC, farfromrefug commented on packages/core/ui/core/view/index.android.ts
> +		const weight = lp.weight;
In fact I would not. I forgot a if lp.gravity which makes 2 calls to native accesser. Need to fix this. The idea is to make sure we don't access those native variables multiple times => multiple jni calls

2020-12-30 19:27 UTC, farfromrefug commented on packages/core/ui/core/view/index.android.ts
> +					lp.gravity = 3 | (gravity & VERTICAL_GRAVITY_MASK); // android.view.Gravity.LEFT
I remember  i copied the way it was done somewhere else. And I didn't want to unecessarly create global module variables. 
But sure I ll change it

2021-07-12 00:27 UTC, NathanWalker approved these changes

2021-08-11 18:31 UTC, merged