fix: requestlayout improvements
NativeScript/NativeScript pull request #9122
Opened 2020-12-30 15:31 UTC by farfromrefug

This is a first pass at improving `requestLayout`.  The biggest improvements are seen on iOS.
* during `applyAllNativeSetters` or `applyPendingNativeSetters` prevent `requestLayout` calls on every property change. Instead call `requestLayout` if needed at the end. This is a big change on iOS as most properties are marked as affecting layout. 
* on top of that dont even call `requestLayout` at all if within `onLoaded`. it is not necessary as the parent with layout itself and thus layout all its children.

With that change, the colors fixes and the android background color change simplification, i see a 5-10%  shorter loading time on android. Tested it with different apps of different complexity.

2020-12-30 16:30 UTC, NathanaelA commented
This looks awesome.  Thanks -- did you run it against the app testing harness?

2020-12-30 19:15 UTC, farfromrefug commented
Which app  are you referring to?

2020-12-30 20:54 UTC, NathanWalker commented
@farfromrefug `npm start` > type `automated.ios` (and you can also run `automated.android`) to kick them off locally.

2020-12-31 07:09 UTC, farfromrefug commented
@NathanWalker thanks was not sure @NathanaelA was refering to another one.

2021-01-29 20:18 UTC, NathanWalker requested changes

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view-base/index.ts
> +	_requetLayoutNeeded = false;
@farfromrefug Could you just fix the spelling here:

```suggestion
	_requestLayoutNeeded = false;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.ios.ts
> +			this._requetLayoutNeeded = true;
```suggestion
			this._requestLayoutNeeded = true;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.android.ts
> +			this._requetLayoutNeeded = true;
```suggestion
			this._requestLayoutNeeded = true;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.android.ts
> +		this._requetLayoutNeeded = false;
```suggestion
		this._requestLayoutNeeded = false;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.ios.ts
> +			this._requetLayoutNeeded = false;
```suggestion
			this._requestLayoutNeeded = false;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.ios.ts
> +		this._requetLayoutNeeded = false;
```suggestion
		this._requestLayoutNeeded = false;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view-base/index.ts
> +		return this._requetLayoutNeeded;
```suggestion
		return this._requestLayoutNeeded;
```

2021-01-29 20:18 UTC, NathanWalker commented on packages/core/ui/core/view/index.ios.ts
> +	requestlayoutIfNeeded() {
Maintain same camel case throughout:
```suggestion
	requestLayoutIfNeeded() {
```

2021-02-01 15:21 UTC, farfromrefug commented
@rigor789 should be all good

2021-02-01 15:23 UTC, rigor789 approved these changes
LGTM

2021-07-12 00:26 UTC, NathanWalker commented
@farfromrefug I'm curious if your fork may have a different setting than most? I've noticed that on all your PR's we can not update the PR with base automatically on github however for all other pr's we are able to. Is there a setting on your fork that may be preventing that? We could help get quite a few of your pr's merged if we can update them with latest master automatically here.

2021-07-12 06:02 UTC, farfromrefug commented
@NathanWalker you mean on my PR s you font have the right to update? I always create PRs from github website but I have to say I almost never ensure the checkbox for collaboration is checked or not. though it should be by default

2021-08-11 18:50 UTC, merged