feat: setSelection method for editable text components
NativeScript/NativeScript pull request #9175
Opened 2021-01-26 15:41 UTC by farfromrefug

this add support for `setSection` for all editable text components

2021-01-26 16:57 UTC, rigor789 approved these changes

2021-01-26 16:57 UTC, rigor789 commented on packages/core/ui/editable-text-base/index.ios.ts
> +			view.selectedTextRange = view.textRangeFromPositionToPosition(view.positionFromPositionOffset(begin, start), view.positionFromPositionOffset(begin, stop));
Perhaps this makes this line a bit more readable
```suggestion
			view.selectedTextRange = view.textRangeFromPositionToPosition(
						view.positionFromPositionOffset(begin, start),
						view.positionFromPositionOffset(begin, stop)
			);
```

2021-01-26 21:29 UTC, NathanWalker requested changes

2021-01-26 21:29 UTC, NathanWalker commented on packages/core/ui/editable-text-base/index.ios.ts
> +		if (stop !== undefined) {
Might be good to wrap all this in conditional to protect against view (android side does it already but always best to be careful with ios as well):
```
if (view) {
```

2021-01-27 11:15 UTC, farfromrefug commented
@NathanWalker not sure why it says changes are requested still. I did the asked changes

2021-01-27 11:56 UTC, rigor789 submitted a review, later dismissed
LGTM - couple formatting issues only.

2021-01-27 11:56 UTC, rigor789 commented on packages/core/ui/editable-text-base/index.ios.ts
> +			}
Formatting seems to be off here - did you run `npm run setup` after cloning the repo to ensure husky & git-hooks are installed? These should then auto-format changed files on commit.

2021-01-27 13:46 UTC, farfromrefug commented on packages/core/ui/editable-text-base/index.ios.ts
> +			}
yes I do and I use eslint. wonder why it does not work. shouldn't it prevent the commit or auto format ?

2021-01-27 14:50 UTC, rigor789 approved these changes

2021-01-28 23:31 UTC, NathanWalker approved these changes

2021-01-28 23:32 UTC, merged