Updated README. md
NativeScript/NativeScript pull request #9528
Opened 2021-08-31 12:55 UTC by Adarshjaiss

I have done some minor grammatical changes in readme file, and simplified some sentences which was creating a little bit problem from the contributors to understand.

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

2021-08-31 13:01 UTC, Adarshjaiss commented
@cla-bot check

2021-09-02 22:56 UTC, NathanWalker commented on README.md
> +## our Other frameworks sources repositories:-
Thank you @Adarshjaiss for these improvements. Everything looks great, although this one sounds a bit funny, how about just:
```
## More source repos
```

If you don't mind making that one adjustment we'd love to get this merged.

2021-09-03 03:29 UTC, Adarshjaiss commented on README.md
> +## our Other frameworks sources repositories:-
@Nathan Walker Thank you sir, for mentoring and reviewing this code. Actually, I have done that silly mistake, I am sorry for that. I am just correcting it. 🙂

2021-09-03 05:36 UTC, NathanWalker requested changes

2021-09-03 05:36 UTC, NathanWalker commented on README.md
> +## our Other frameworks sources repositories:-
You’ll notice in the changeset above in green, no further change has been pushed yet. Perhaps you made the change locally but haven’t committed and pushed it yet?

2021-09-04 03:16 UTC, Adarshjaiss commented
i am sorry for that i have troubled you sir. but now i have fixed all changes and the pr is ready to go.

2021-09-06 19:50 UTC, NathanWalker approved these changes

2021-09-06 19:51 UTC, merged