fix: Apply proper border radius to box shadow and view sublayers
NativeScript/NativeScript pull request #9881
Opened 2022-04-26 19:04 UTC by CatchABus

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
In iOS:
- Border radius is miscalculated for drop-shadow
- Gradient background border radius is miscalculated when there is drop-shadow

I found those problems while using an iPad. Box-shadow radius was probably miscalculated because of a scale factor that may be higher than 1.
![D1C14C66-80AC-4594-A7ED-AC2BA2CE741E](https://user-images.githubusercontent.com/55595100/165373557-1fdb8b0e-c5e6-48f3-a78d-0f67aa7fde13.png)

## What is the new behavior?
Border radius will be properly calculated for view box-shadow and sublayers. It seems that `toDeviceIndependentPixels` works better and returns the same value as the rest of applied view border-radiuses.
This change will also attempt to apply corner radius to all sublayers. Sublayers will usually consist of a gradient layer and a border layer.
There are also cases that border layer has sublayers but there is a need for a whole refactor to make those look good, that is why we apply radius to top-level layers for now.

Fixes/Closes #9869 .

2022-04-27 22:08 UTC, NathanWalker approved these changes

2022-04-27 22:12 UTC, NathanWalker requested changes

2022-04-27 22:12 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +		for (let childLayer of nativeView.layer.sublayers) {
@CatchABus nativeView.layer.sublayers is a NSArray I believe so don't believe that for/of would work there. Likely need (would update condition too):
```
if (nativeView?.layer?.sublayers?.count) {
  for (let i = 0; i < nativeView.layer.sublayers.count; i++) { 
    nativeView.layer.sublayers.objectAtIndex(i).cornerRadius = cornerRadis
  }
}
```

2022-04-27 22:20 UTC, CatchABus commented on packages/core/ui/styling/background.ios.ts
> +		for (let childLayer of nativeView.layer.sublayers) {
@NathanWalker Strange thought it may seem, this loop works and I'm not sure why either.
At first, I used it in one of my plugins some time ago and I thought that runtime was designed to support this kind of iteration.

I can change it to a `for` loop as suggested, but it would also be interesting to know why it works that way too.

2022-04-27 22:31 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +		for (let childLayer of nativeView.layer.sublayers) {
Might check if project testing against is using v8 or JSC runtime? To be safest I would use NSArray iterator as that is for sure what this is.

2022-04-27 22:49 UTC, CatchABus commented on packages/core/ui/styling/background.ios.ts
> +		for (let childLayer of nativeView.layer.sublayers) {
> Might check if project testing against is using v8 or JSC runtime? To be safest I would use NSArray iterator as that is for sure what this is.

I'm using v8.
I also prefer the safest approach so I updated loops as pointed out above. Please let me know if there is more I can do to improve this.

2022-04-29 02:50 UTC, NathanWalker requested changes

2022-04-29 02:50 UTC, NathanWalker commented on packages/core/ui/styling/background.ios.ts
> +			subLayer.cornerRadius = cornerRadius;
To reduce native calls, one last touch here will help ensure this is as performant as possible.
```
const sublayers = nativeView?.layer?.sublayers;
if (sublayers) {
  for (let i = 0; i < sublayers.count; i++) {
			nativeView.layer.sublayers.objectAtIndex(i).cornerRadius = cornerRadius;
  }
}
```
All throughout core we try to limit unneeded references and native property traversal to absolutely minimum - helps perf in the long run.

2022-04-30 17:33 UTC, CatchABus commented on packages/core/ui/styling/background.ios.ts
> +			subLayer.cornerRadius = cornerRadius;
> To reduce native calls, one last touch here will help ensure this is as performant as possible.
> 
> ```
> const sublayers = nativeView?.layer?.sublayers;
> if (sublayers) {
>   for (let i = 0; i < sublayers.count; i++) {
>     sublayers.objectAtIndex(i).cornerRadius = cornerRadius;
>   }
> }
> ```
> 
> All throughout core we try to limit unneeded references and native property traversal to absolute minimum - helps perf in the long run.

Done! :)

2022-04-30 17:59 UTC, merged

2022-05-04 22:49 UTC, CatchABus commented
@NathanWalker Whenever possible, I believe we should revert this one as it's unsafe.
There is the case that corner radius will cause unexpected results if children are added to view "before" view shadow is applied for some reason.
I have thought of a good way to solve this and maintain a good performance at the same time.

2022-05-05 06:29 UTC, farfromrefug commented
@CatchABus if of any interest to you I had done this in another cross platform framework Titanium. I can fins the code if you need

2022-05-05 06:48 UTC, CatchABus commented
> @CatchABus if of any interest to you I had done this in another cross platform framework Titanium. I can fins the code if you need

Sure! It could be a good addition!

Note: I tend to think that using main layer with masksToBounds and clipsToBounds for shadows will keep causing trouble in the future. Maybe we should also consider the use of a sublayer for shadows as one solution?

2022-05-05 07:20 UTC, farfromrefug commented
@CatchABus it s all here https://github.com/Akylas/titanium_mobile/blob/master/iphone/Classes/TiUIView.m#L610= . If you have any question ping me on discord

2022-05-05 12:42 UTC, rigor789 commented
> Note: I tend to think that using main layer with masksToBounds and clipsToBounds for shadows will keep causing trouble in the future. Maybe we should also consider the use of a sublayer for shadows as one solution?

I agree - I was working on the initial box-shadow implementation and had tinkered with the idea of using proper sublayers for shadows - allowing stacking multiple shadows etc, however there was a major roadblock (fixable I would imagine, but still was major)...

Given an ios view, you can add as many subviews as you want, however you cannot move them behind the parent view, only above it (at least if I remember correctly, been a while...) - which meant we couldn't easily add a shadow layer to existing views and move them behind the view. The approach I was playing around with was adding an extra parent view to hold the original view + the shadow layers, but managing that was kinda tricky as core View handling is set up to handle the root view and not anything above.

Wrapping every view in a extra view seemed like a bad solution, as it would double the number of views rendered even if most of them don't render a shadow.

Ideally the following structure could work:

```
  View
    -> nativeView (UIView or whatever)
```

```
  View with shadow
    -> decorView
       -> nativeView (UIView or whatever)
       -> shadowLayer1
       -> shadowLayer2
       -> etc.
```

2022-05-05 13:02 UTC, CatchABus commented
> > Note: I tend to think that using main layer with masksToBounds and clipsToBounds for shadows will keep causing trouble in the future. Maybe we should also consider the use of a sublayer for shadows as one solution?
> 
> I agree - I was working on the initial box-shadow implementation and had tinkered with the idea of using proper sublayers for shadows - allowing stacking multiple shadows etc, however there was a major roadblock (fixable I would imagine, but still was major)...
> 
> Given an ios view, you can add as many subviews as you want, however you cannot move them behind the parent view, only above it (at least if I remember correctly, been a while...) - which meant we couldn't easily add a shadow layer to existing views and move them behind the view. The approach I was playing around with was adding an extra parent view to hold the original view + the shadow layers, but managing that was kinda tricky as core View handling is set up to handle the root view and not anything above.
> 
> Wrapping every view in a extra view seemed like a bad solution, as it would double the number of views rendered even if most of them don't render a shadow.
> 
> Ideally the following structure could work:
> 
> ```
>   View
>     -> nativeView (UIView or whatever)
> ```
> 
> ```
>   View with shadow
>     -> decorView
>        -> nativeView (UIView or whatever)
>        -> shadowLayer1
>        -> shadowLayer2
>        -> etc.
> ```

Perhaps, this issue gets solved using `insertSublayerAtIndex` or setting layer `zPosition` to negative value (default is 0 for all layers).
I'm using those in my neumorphism shadow plugin.

2022-05-05 13:05 UTC, rigor789 commented
> > > Note: I tend to think that using main layer with masksToBounds and clipsToBounds for shadows will keep causing trouble in the future. Maybe we should also consider the use of a sublayer for shadows as one solution?
> > 
> > 
> > I agree - I was working on the initial box-shadow implementation and had tinkered with the idea of using proper sublayers for shadows - allowing stacking multiple shadows etc, however there was a major roadblock (fixable I would imagine, but still was major)...
> > Given an ios view, you can add as many subviews as you want, however you cannot move them behind the parent view, only above it (at least if I remember correctly, been a while...) - which meant we couldn't easily add a shadow layer to existing views and move them behind the view. The approach I was playing around with was adding an extra parent view to hold the original view + the shadow layers, but managing that was kinda tricky as core View handling is set up to handle the root view and not anything above.
> > Wrapping every view in a extra view seemed like a bad solution, as it would double the number of views rendered even if most of them don't render a shadow.
> > Ideally the following structure could work:
> > ```
> >   View
> >     -> nativeView (UIView or whatever)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >   View with shadow
> >     -> decorView
> >        -> nativeView (UIView or whatever)
> >        -> shadowLayer1
> >        -> shadowLayer2
> >        -> etc.
> > ```
> 
> Perhaps, this issue gets solved using `insertSublayerAtIndex` or setting layer `zPosition` to negative value (default is 0 for all layers). I'm using those in my neumorphism shadow plugin.

I'm not sure - I'm pretty sure I tried every possible combination, and could not move my shadow layer below the actual view - inserting it at various indices or zPositions, was always above the view. But if that works, that'd be perfect 👍

2022-05-05 17:25 UTC, CatchABus commented
@rigor789 I'm not sure if I understood correctly but I have this plugin for neumorphism styling: https://github.com/CatchABus/nativescript-plugins/tree/master/packages/ui-neumorphiclayout
It uses 2 sublayers because support for 2 different shadows is needed. So far, I have nested children inside those views without problems.
Maybe, this concept could serve for adding multiple shadows support to NS.

2022-05-05 18:15 UTC, rigor789 commented
@CatchABus I just remembered - I never deleted the tests I did here (they are ignored, as we return early): https://github.com/NativeScript/NativeScript/blob/eb4c4a3091a347b9cf8f2fdf5593f20938464ab3/packages/core/utils/native-helper.ios.ts#L126-L203

removing the early return yields the following: 
![Screenshot 2022-05-05 at 8 06 58 PM](https://user-images.githubusercontent.com/879060/166985755-090bd061-7934-4c5c-9a3e-86db1bcc28d4.png)

With some logging - here are the resulting layers:

![Screenshot 2022-05-05 at 8 08 38 PM](https://user-images.githubusercontent.com/879060/166986008-dacd2f50-1c25-4dbf-88f3-556248da5663.png)

Haven't had a closer look at your plugin, or what it does differently - but if you want you can try the above:
 - run the toolbox app -> box-shadow -> toggle solid background -> apply shadow
 - comment out the return in the native-helper.ios.ts and let the test logic run
 - make any adjustments in there to see if there's a way to move that shadow layer below the actual view...

2022-05-07 14:26 UTC, CatchABus commented
> @CatchABus I just remembered - I never deleted the tests I did here (they are ignored, as we return early):
> 
> https://github.com/NativeScript/NativeScript/blob/eb4c4a3091a347b9cf8f2fdf5593f20938464ab3/packages/core/utils/native-helper.ios.ts#L126-L203
> 
> removing the early return yields the following: ![Screenshot 2022-05-05 at 8 06 58 PM](https://user-images.githubusercontent.com/879060/166985755-090bd061-7934-4c5c-9a3e-86db1bcc28d4.png)
> 
> With some logging - here are the resulting layers:
> 
> ![Screenshot 2022-05-05 at 8 08 38 PM](https://user-images.githubusercontent.com/879060/166986008-dacd2f50-1c25-4dbf-88f3-556248da5663.png)
> 
> Haven't had a closer look at your plugin, or what it does differently - but if you want you can try the above:
> 
> * run the toolbox app -> box-shadow -> toggle solid background -> apply shadow
> * comment out the return in the native-helper.ios.ts and let the test logic run
> * make any adjustments in there to see if there's a way to move that shadow layer below the actual view...
> 
> I guess the difference is that in your plugin you have a `fillColor` property - and not the regular `backgroundColor`/`backgroundImage` I guess, so you have more control of the drawing there?

I see, I get it now! To solve this, we can apply view background color to shadow layer.
After all, it's only the color that's on the bottom.
![Screenshot 2022-05-07 at 5 24 52 PM](https://user-images.githubusercontent.com/55595100/167258496-828d3495-1e22-4039-b5ce-a8f5c135f0fe.png)


Seeing where this goes, I think we should stop setting background color to native views directly and have a `backgroundLayer` that replaces shadow and border layers functionality, and background color would also apply to it. It could be used for multiple purposes.