fix(core): android wrong background state + current value accessors
NativeScript/NativeScript pull request #9883
Opened 2022-04-27 07:12 UTC by farfromrefug

This fixes a bug with my recent addition of `backgroung/foreground` events.
It also adds getters `inBackground` and `suspended` in `application-common` to query the current value for both iOS/Android

2022-04-27 22:05 UTC, NathanWalker approved these changes

2022-04-28 06:13 UTC, farfromrefug commented
@NathanWalker maybe the getters name should.be different.let me know if you think there would be better names

2022-04-30 17:51 UTC, NathanWalker requested changes

2022-04-30 17:51 UTC, NathanWalker commented on packages/core/application/index.android.ts
> +	}
@farfromrefug nice changes here, will definitely help. Let's go with this naming, I think will be more clear:
```
get isPaused() {
  return suspended;
}
get isInBackground() {
  return inBackground;
}
```

2022-04-30 18:20 UTC, farfromrefug commented on packages/core/application/index.android.ts
> +	}
@NathanWalker i was more talking about the naming in application-common.ts https://github.com/Akylas/NativeScript/blob/backgroundevent_fix/packages/core/application/application-common.ts#L173=
The change you propose is a breaking change as it was already available. Are we sure we want that to change?
we could actually deprecate the android file one. Now people should use the common one as it works on iOS and android

2022-04-30 20:15 UTC, NathanWalker commented on packages/core/application/index.android.ts
> +	}
Oh! I see my bad. Let’s keep what you have then. Will include in next alpha.

2022-05-01 03:53 UTC, NathanWalker commented on packages/core/application/index.android.ts
> +	}
I agree with deprecating the old one and just make single consistent one from `Application.isPaused` for example - would behave same for all platforms. We can do that separately on the alpha branch itself.

2022-05-01 03:54 UTC, merged