feat(core): support font-variation-settings
NativeScript/NativeScript pull request #9995
Opened 2022-08-16 23:32 UTC by lekhmanrus

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
[`font-variation-settings`](https://drafts.csswg.org/css-fonts/#font-variation-settings-def) CSS rule not supported.

## What is the new behavior?
`font-variation-settings` is supported on Android and I'm thinking about the proper implementation for iOS. I guess it should be similar to VFont - using attributes. It would be fine if someone has any suggestions/directions here. 🙂

2022-08-17 06:34 UTC, farfromrefug commented
@lekhmanrus warning the font builder was only added in API 29. if I read your changes right it will crash on < 29.

2022-08-17 15:02 UTC, lekhmanrus commented
@farfromrefug, [Typeface.Builder](https://developer.android.com/reference/android/graphics/Typeface.Builder#Builder(java.io.File)) added in API level 26. But yeah - I probably need to add a few conditions in the code.

2022-08-18 12:05 UTC, farfromrefug commented
@lekhmanrus you are right. it says 26. it is weird as I am sure I saw an android doc saying 29... anyway...

2022-08-18 14:45 UTC, lekhmanrus commented
@farfromrefug, I guess it was [Font.Builder](https://developer.android.com/reference/android/graphics/fonts/Font.Builder) - it says 29. But I use [Typeface.Builder](https://developer.android.com/reference/android/graphics/Typeface.Builder#Builder(java.io.File)) here.

2022-11-18 05:11 UTC, NathanWalker requested changes

2022-11-18 05:11 UTC, NathanWalker commented on packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
> +	static getSystemFont(size: number, weight: UIFontWeight, italic: boolean, symbolicTraits: UIFontDescriptorSymbolicTraits): UIFont;
This doesn't look right - you can `ns typings ios` inside of `apps/toolbox` to regen the typings and put this typing back to get it correct. Should still be `getSystemFontWeightItalicSymbolicTraits` I believe.

2022-11-18 20:57 UTC, lekhmanrus commented on packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
> +	static getSystemFont(size: number, weight: UIFontWeight, italic: boolean, symbolicTraits: UIFontDescriptorSymbolicTraits): UIFont;
Hi @NathanWalker, Sorry currently do not have Mac in front of me - I'll try that next week.
But why do we need `getSystemFontWeightItalicSymbolicTraits`? We have 0 matches for that in the repo. Where it comes from?

2022-11-19 01:11 UTC, NathanWalker commented on packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
> +	static getSystemFont(size: number, weight: UIFontWeight, italic: boolean, symbolicTraits: UIFontDescriptorSymbolicTraits): UIFont;
That is a platform API from iOS therefore it's signature comes from the metadata (`ns typings ios`) - it may or may not be used within scope of core however the typings here are important to match always what the generation determines (should never be manually adjusted).

2022-11-22 23:21 UTC, lekhmanrus commented on packages/core/platforms/ios/typings/objc!NativeScriptUtils.d.ts
> +	static getSystemFont(size: number, weight: UIFontWeight, italic: boolean, symbolicTraits: UIFontDescriptorSymbolicTraits): UIFont;
Hi @NathanWalker,
Thanks, just committed typings. 🙂

2022-11-24 03:28 UTC, NathanWalker approved these changes

2022-11-24 04:57 UTC, merged